language: perl
matrix:
  include:
  - perl: '5.12'
    dist: trusty
  - perl: '5.14'
  - perl: '5.16'
  - perl: '5.18'
  - perl: '5.20'
  - perl: '5.22'
  - perl: '5.24'
  - perl: '5.26'
  - perl: '5.28'
  - perl: '5.30'
notifications:
  email: false
  slack:
    secure: Mp9S0Qsmmh7HecgMXRhRzqTJeQzvL9i80xJziBUQgMQbQkMya3IFXo6kjbnySkE9nCRbI3POLDhD7y+TPiglCdRNIgtPCQgRY7cGrqPJUALsqWCsUx9wsWU5g5aOqndjZFNs13WW2dVPB4SrWqlbQ6Xx9ezYrFDZ/9Nk39SK3ILkFXxKOcf3lt60mrAe+d5dfPToVyddwSZ9wp1Rs4NzaV+uRbrN4Ott+ErevKI/USN0n5XLMfNOq5yPuuMdExH1mP5i3Y9VVrkTGKfzNXpbjRWAIJECRPYvTfpvoeFUSq6hAXY5QLfFcfJDFpFhuBbVZi/3I069nNsy8OB/fY/kxXi5CyPWHZ5FmhjEjqWLVAaCZHh09/Cuv0eqgLlpZaUCOTuEozRxnVHvti08ypJ9fLwbK32iAaHZnCWfrn8hDRZBrFin6MfARUCuDXMRGDrYjR1krKWfz/45Un60G25kzlMBhfAaOHkFmFH2MbLNIQyrajKpQ66m4oxvEgP7rzg9rEwhdBdme0GFUmDXGOwdtJxklDD9/YTGu++zQC13RsEztseG5kknugY/3ny8+2ROIyIjUeV5KPfkRvTdNL4/E90FdPOlUvAS+4ofwgqu+qDh+MzsCmG70WKO5GoWF6AH3cdmcedppwJ74zmgYO0F1eKicDWZIg+5WmxpRn4JRvs=
